
version: 2

metrics:
  - name: review_data_met
    label: review
    model: ref('review_data')
    description: "The Review"

    type: count
    sql: customer_id # superfluous here, but shown as an example

    timestamp: orde_date
    time_grains: [day, week, month]

    dimensions:
      - customer_id
      
    
   


sources:
  - name: public
    tables:
      - name: order_new
      - name: order_table
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: order_date
 

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
