
version: 2

models:
    - name: my_first1_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
           

    - name: my_second2_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    